apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketingCustomer
  labels:
    app: marketingCustomer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketingCustomer
  template:
    metadata:
      labels:
        app: marketingCustomer
    spec:
      containers:
        - name: marketingCustomer
          image: username/marketingCustomer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5